Device is cpu
mnist_svhn
/home/agathe/Code/miniconda3/envs/myenv38/lib/python3.8/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484683044/work/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "src/bivae/main.py", line 73, in <module>
    model = modelC(args).to(device)
  File "/home/agathe/Code/mmvae/src/bivae/models/mmvae/mmvae_mnist_svhn.py", line 47, in __init__
    super(MNIST_SVHN, self).__init__(params, vaes)
  File "/home/agathe/Code/mmvae/src/bivae/models/mmvae/mmvae.py", line 26, in __init__
    super(MMVAE, self).__init__(params, vaes)
  File "/home/agathe/Code/mmvae/src/bivae/models/multi_vaes.py", line 54, in __init__
    self.px_z = [ dist_dict[r] for r in params.recon_losses]
AttributeError: 'Namespace' object has no attribute 'recon_losses'